default:
  tags:
    - docker

variables:
  GITLAB_TOKEN: $GORELEASER_GITLAB_TOKEN
  GOPROXY: "https://go-registry.int.similarweb.io"

stages:
  - release

release:
  stage: release
  image:
    name: goreleaser/goreleaser:v1.15.2
    entrypoint: [""]
  only:
    - tags
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
  script:
    - make release
