default:
  tags:
    - docker

variables:
  GITLAB_TOKEN: $GORELEASER_GITLAB_TOKEN
  GOPROXY: "https://go-registry.int.similarweb.io"

stages:
  - lint
  - tests
  - release

linters:
  stage: lint
  image: golangci/golangci-lint:v1.55.2
  cache:
    paths:
      - /root/.cache/golangci-lint
    key:
      files:
        - go.sum
  script:
    - golangci-lint run --new -v ./...
  only:
    - merge_requests
  needs: []

tests:
  stage: tests
  image: golang:1.22.0-alpine
  script:
    - go test ./... -v
  only:
    - merge_requests
  needs: []

release:
  stage: release
  image:
    name: goreleaser/goreleaser:v1.15.2
    entrypoint: [""]
  only:
    - tags
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
  script:
    - make release
