project_name: bbox
version: 2
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: 
      - -s -w -X bbox/version.version={{.Version}} -X bbox/version.commit={{.Commit}} -X bbox/version.date={{.Date}} -X bbox/version.builtBy=goreleaser

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

      
brews:
  - name: bbox
    repository:
      owner: similarweb
      name: homebrew-tap
    homepage: "https://github.com/similarweb"
    description: "bbox is a CLI tool for interacting with TeamCity and other CI/CD tools."
    install: |
      bin.install "bbox"

