project_name: bbox
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    ldflags: "-X gitlab.int.similarweb.io/infrastructure/bbox/version.version={{.Version}}"
    goarch:
      - amd64
      - arm64
release:
  gitlab:
    owner: infrastructure
    name: bbox

archives:
  - format: tar.gz

gitlab_urls:
  api: https://gitlab.int.similarweb.io/api/v4/
  download: https://gitlab.int.similarweb.io
  skip_tls_verify: true
  use_package_registry: true

