project_name: bbox
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    ldflags: "-X gitlab.similarweb.io/infrastructure/bbox/cmd.Version={{.Version}} -X gitlab.similarweb.io/infrastructure/bbox/cmd.Commit={{.Commit}} "
    goarch:
      - amd64
      - arm64
release:
  gitlab:
    owner: infrastructure
    name: bbox

archives:
  - format: tar.gz

gitlab_urls:
  api: http://gitlab.similarweb.io/api/v4/
  download: http://gitlab.similarweb.io
  skip_tls_verify: true
  use_package_registry: true

