name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      repository-projects: write 
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3
      - 
        name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  push:
    runs-on: ubuntu-latest
    needs: goreleaser
    permissions:
      contents: write
      actions: write
      repository-projects: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: similarweb/bbox
          tag_with_ref: true
          path: /github/workspace
