name: Tag Version

on:
  push:
    branches:
      - master
    paths:
      - "version/version.txt"

permissions:
  contents: write

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Read version from version.txt
        id: read_version
        run: |
          VERSION=$(cat version/version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${{ env.VERSION }}" -m "Release version ${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
